export interface StaticLanguage {
  /** The language code (ISO 639-1) */
  code: string
  name: string
  native_name: string
  is_rtl: boolean
}

export const languages: StaticLanguage[] = [
  {
    code: 'af',
    name: 'Afrikaans',
    native_name: 'Afrikaans',
    is_rtl: false,
  },
  {
    code: 'ak',
    name: 'Akan',
    native_name: 'Akan',
    is_rtl: false,
  },
  {
    code: 'sq',
    name: 'Albanian',
    native_name: 'Shqip',
    is_rtl: false,
  },
  {
    code: 'am',
    name: 'Amharic',
    native_name: 'አማርኛ',
    is_rtl: false,
  },
  {
    code: 'ar',
    name: 'Arabic',
    native_name: 'العربية',
    is_rtl: true,
  },
  {
    code: 'hy',
    name: 'Armenian',
    native_name: 'Հայերեն',
    is_rtl: false,
  },
  {
    code: 'as',
    name: 'Assamese',
    native_name: 'অসমীয়া',
    is_rtl: false,
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    native_name: 'Azərbaycan',
    is_rtl: false,
  },
  {
    code: 'bm',
    name: 'Bambara',
    native_name: 'Bamanankan',
    is_rtl: false,
  },
  {
    code: 'bn',
    name: 'Bangla',
    native_name: 'বাংলা',
    is_rtl: false,
  },
  {
    code: 'eu',
    name: 'Basque',
    native_name: 'Euskara',
    is_rtl: false,
  },
  {
    code: 'be',
    name: 'Belarusian',
    native_name: 'Беларуская',
    is_rtl: false,
  },
  {
    code: 'bs',
    name: 'Bosnian',
    native_name: 'Bosanski',
    is_rtl: false,
  },
  {
    code: 'br',
    name: 'Breton',
    native_name: 'Brezhoneg',
    is_rtl: false,
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    native_name: 'Български',
    is_rtl: false,
  },
  {
    code: 'my',
    name: 'Burmese',
    native_name: 'မြန်မာ',
    is_rtl: false,
  },
  {
    code: 'ca',
    name: 'Catalan',
    native_name: 'Català',
    is_rtl: false,
  },
  {
    code: 'ce',
    name: 'Chechen',
    native_name: 'Нохчийн',
    is_rtl: false,
  },
  {
    code: 'zh',
    name: 'Chinese',
    native_name: '中文',
    is_rtl: false,
  },
  {
    code: 'kw',
    name: 'Cornish',
    native_name: 'Kernewek',
    is_rtl: false,
  },
  {
    code: 'hr',
    name: 'Croatian',
    native_name: 'Hrvatski',
    is_rtl: false,
  },
  {
    code: 'cs',
    name: 'Czech',
    native_name: 'Čeština',
    is_rtl: false,
  },
  {
    code: 'da',
    name: 'Danish',
    native_name: 'Dansk',
    is_rtl: false,
  },
  {
    code: 'nl',
    name: 'Dutch',
    native_name: 'Nederlands',
    is_rtl: false,
  },
  {
    code: 'dz',
    name: 'Dzongkha',
    native_name: 'རྫོང་ཁ',
    is_rtl: false,
  },
  {
    code: 'en',
    name: 'English',
    native_name: 'English',
    is_rtl: false,
  },
  {
    code: 'eo',
    name: 'Esperanto',
    native_name: 'Esperanto',
    is_rtl: false,
  },
  {
    code: 'et',
    name: 'Estonian',
    native_name: 'Eesti',
    is_rtl: false,
  },
  {
    code: 'ee',
    name: 'Ewe',
    native_name: 'Eʋegbe',
    is_rtl: false,
  },
  {
    code: 'fo',
    name: 'Faroese',
    native_name: 'Føroyskt',
    is_rtl: false,
  },
  {
    code: 'fil',
    name: 'Filipino',
    native_name: 'Filipino',
    is_rtl: false,
  },
  {
    code: 'fi',
    name: 'Finnish',
    native_name: 'Suomi',
    is_rtl: false,
  },
  {
    code: 'fr',
    name: 'French',
    native_name: 'Français',
    is_rtl: false,
  },
  {
    code: 'ff',
    name: 'Fulah',
    native_name: 'Fulfulde',
    is_rtl: false,
  },
  {
    code: 'gl',
    name: 'Galician',
    native_name: 'Galego',
    is_rtl: false,
  },
  {
    code: 'lg',
    name: 'Ganda',
    native_name: 'Luganda',
    is_rtl: false,
  },
  {
    code: 'ka',
    name: 'Georgian',
    native_name: 'ქართული',
    is_rtl: false,
  },
  {
    code: 'de',
    name: 'German',
    native_name: 'Deutsch',
    is_rtl: false,
  },
  {
    code: 'el',
    name: 'Greek',
    native_name: 'Ελληνικά',
    is_rtl: false,
  },
  {
    code: 'gu',
    name: 'Gujarati',
    native_name: 'ગુજરાતી',
    is_rtl: false,
  },
  {
    code: 'ha',
    name: 'Hausa',
    native_name: 'Hausa',
    is_rtl: false,
  },
  {
    code: 'hi',
    name: 'Hindi',
    native_name: 'हिन्दी',
    is_rtl: false,
  },
  {
    code: 'hu',
    name: 'Hungarian',
    native_name: 'Magyar',
    is_rtl: false,
  },
  {
    code: 'is',
    name: 'Icelandic',
    native_name: 'Íslenska',
    is_rtl: false,
  },
  {
    code: 'ig',
    name: 'Igbo',
    native_name: 'Igbo',
    is_rtl: false,
  },
  {
    code: 'id',
    name: 'Indonesian',
    native_name: 'Bahasa Indonesia',
    is_rtl: false,
  },
  {
    code: 'ia',
    name: 'Interlingua',
    native_name: 'Interlingua',
    is_rtl: false,
  },
  {
    code: 'ga',
    name: 'Irish',
    native_name: 'Gaeilge',
    is_rtl: false,
  },
  {
    code: 'it',
    name: 'Italian',
    native_name: 'Italiano',
    is_rtl: false,
  },
  {
    code: 'ja',
    name: 'Japanese',
    native_name: '日本語',
    is_rtl: false,
  },
  {
    code: 'jv',
    name: 'Javanese',
    native_name: 'Basa Jawa',
    is_rtl: false,
  },
  {
    code: 'kl',
    name: 'Kalaallisut',
    native_name: 'Kalaallisut',
    is_rtl: false,
  },
  {
    code: 'kn',
    name: 'Kannada',
    native_name: 'ಕನ್ನಡ',
    is_rtl: false,
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    native_name: 'कॉशुर',
    is_rtl: false,
  },
  {
    code: 'kk',
    name: 'Kazakh',
    native_name: 'Қазақ тілі',
    is_rtl: false,
  },
  {
    code: 'km',
    name: 'Khmer',
    native_name: 'ខ្មែរ',
    is_rtl: false,
  },
  {
    code: 'ki',
    name: 'Kikuyu',
    native_name: 'Gĩkũyũ',
    is_rtl: false,
  },
  {
    code: 'rw',
    name: 'Kinyarwanda',
    native_name: 'Kinyarwanda',
    is_rtl: false,
  },
  {
    code: 'ko',
    name: 'Korean',
    native_name: '한국어',
    is_rtl: false,
  },
  {
    code: 'ku',
    name: 'Kurdish',
    native_name: 'کوردی',
    is_rtl: true,
  },
  {
    code: 'ky',
    name: 'Kyrgyz',
    native_name: 'Кыргызча',
    is_rtl: false,
  },
  {
    code: 'lo',
    name: 'Lao',
    native_name: 'ລາວ',
    is_rtl: false,
  },
  {
    code: 'lv',
    name: 'Latvian',
    native_name: 'Latviešu',
    is_rtl: false,
  },
  {
    code: 'ln',
    name: 'Lingala',
    native_name: 'Lingála',
    is_rtl: false,
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    native_name: 'Lietuvių',
    is_rtl: false,
  },
  {
    code: 'lu',
    name: 'Luba-Katanga',
    native_name: 'Tshiluba',
    is_rtl: false,
  },
  {
    code: 'lb',
    name: 'Luxembourgish',
    native_name: 'Lëtzebuergesch',
    is_rtl: false,
  },
  {
    code: 'mk',
    name: 'Macedonian',
    native_name: 'Македонски',
    is_rtl: false,
  },
  {
    code: 'mg',
    name: 'Malagasy',
    native_name: 'Malagasy',
    is_rtl: false,
  },
  {
    code: 'ms',
    name: 'Malay',
    native_name: 'Bahasa Melayu',
    is_rtl: false,
  },
  {
    code: 'ml',
    name: 'Malayalam',
    native_name: 'മലയാളം',
    is_rtl: false,
  },
  {
    code: 'mt',
    name: 'Maltese',
    native_name: 'Malti',
    is_rtl: false,
  },
  {
    code: 'gv',
    name: 'Manx',
    native_name: 'Gaelg',
    is_rtl: false,
  },
  {
    code: 'mr',
    name: 'Marathi',
    native_name: 'मराठी',
    is_rtl: false,
  },
  {
    code: 'mn',
    name: 'Mongolian',
    native_name: 'Монгол',
    is_rtl: false,
  },
  {
    code: 'mi',
    name: 'Māori',
    native_name: 'Māori',
    is_rtl: false,
  },
  {
    code: 'ne',
    name: 'Nepali',
    native_name: 'नेपाली',
    is_rtl: false,
  },
  {
    code: 'nd',
    name: 'North Ndebele',
    native_name: 'isiNdebele',
    is_rtl: false,
  },
  {
    code: 'se',
    name: 'Northern Sami',
    native_name: 'Davvisámegiella',
    is_rtl: false,
  },
  {
    code: 'no',
    name: 'Norwegian',
    native_name: 'Norsk',
    is_rtl: false,
  },
  {
    code: 'nb',
    name: 'Norwegian (Bokmål)',
    native_name: 'Norsk bokmål',
    is_rtl: false,
  },
  {
    code: 'or',
    name: 'Odia',
    native_name: 'ଓଡ଼ିଆ',
    is_rtl: false,
  },
  {
    code: 'om',
    name: 'Oromo',
    native_name: 'Oromoo',
    is_rtl: false,
  },
  {
    code: 'os',
    name: 'Ossetic',
    native_name: 'Ирон',
    is_rtl: false,
  },
  {
    code: 'ps',
    name: 'Pashto',
    native_name: 'پښتو',
    is_rtl: true,
  },
  {
    code: 'fa',
    name: 'Persian',
    native_name: 'فارسی',
    is_rtl: true,
  },
  {
    code: 'pl',
    name: 'Polish',
    native_name: 'Polski',
    is_rtl: false,
  },
  {
    code: 'pt',
    name: 'Portuguese',
    native_name: 'Português',
    is_rtl: false,
  },
  {
    code: 'pa',
    name: 'Punjabi',
    native_name: 'ਪੰਜਾਬੀ',
    is_rtl: false,
  },
  {
    code: 'qu',
    name: 'Quechua',
    native_name: 'Runa Simi',
    is_rtl: false,
  },
  {
    code: 'ro',
    name: 'Romanian',
    native_name: 'Română',
    is_rtl: false,
  },
  {
    code: 'rm',
    name: 'Romansh',
    native_name: 'Rumantsch',
    is_rtl: false,
  },
  {
    code: 'rn',
    name: 'Rundi',
    native_name: 'Ikirundi',
    is_rtl: false,
  },
  {
    code: 'ru',
    name: 'Russian',
    native_name: 'Русский',
    is_rtl: false,
  },
  {
    code: 'sg',
    name: 'Sango',
    native_name: 'Sängö',
    is_rtl: false,
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    native_name: 'संस्कृतम्',
    is_rtl: false,
  },
  {
    code: 'sc',
    name: 'Sardinian',
    native_name: 'Sardu',
    is_rtl: false,
  },
  {
    code: 'gd',
    name: 'Scottish Gaelic',
    native_name: 'Gàidhlig',
    is_rtl: false,
  },
  {
    code: 'sr',
    name: 'Serbian',
    native_name: 'Српски',
    is_rtl: false,
  },
  {
    code: 'sn',
    name: 'Shona',
    native_name: 'chiShona',
    is_rtl: false,
  },
  {
    code: 'ii',
    name: 'Sichuan Yi',
    native_name: 'ꆈꌠꉙ',
    is_rtl: false,
  },
  {
    code: 'sd',
    name: 'Sindhi',
    native_name: 'سنڌي',
    is_rtl: true,
  },
  {
    code: 'si',
    name: 'Sinhala',
    native_name: 'සිංහල',
    is_rtl: false,
  },
  {
    code: 'sk',
    name: 'Slovak',
    native_name: 'Slovenčina',
    is_rtl: false,
  },
  {
    code: 'sl',
    name: 'Slovenian',
    native_name: 'Slovenščina',
    is_rtl: false,
  },
  {
    code: 'so',
    name: 'Somali',
    native_name: 'Soomaali',
    is_rtl: false,
  },
  {
    code: 'es',
    name: 'Spanish',
    native_name: 'Español',
    is_rtl: false,
  },
  {
    code: 'su',
    name: 'Sundanese',
    native_name: 'Basa Sunda',
    is_rtl: false,
  },
  {
    code: 'sw',
    name: 'Swahili',
    native_name: 'Kiswahili',
    is_rtl: false,
  },
  {
    code: 'sv',
    name: 'Swedish',
    native_name: 'Svenska',
    is_rtl: false,
  },
  {
    code: 'tg',
    name: 'Tajik',
    native_name: 'Тоҷикӣ',
    is_rtl: false,
  },
  {
    code: 'ta',
    name: 'Tamil',
    native_name: 'தமிழ்',
    is_rtl: false,
  },
  {
    code: 'tt',
    name: 'Tatar',
    native_name: 'Татарча',
    is_rtl: false,
  },
  {
    code: 'te',
    name: 'Telugu',
    native_name: 'తెలుగు',
    is_rtl: false,
  },
  {
    code: 'th',
    name: 'Thai',
    native_name: 'ไทย',
    is_rtl: false,
  },
  {
    code: 'bo',
    name: 'Tibetan',
    native_name: 'བོད་ཡིག',
    is_rtl: false,
  },
  {
    code: 'ti',
    name: 'Tigrinya',
    native_name: 'ትግርኛ',
    is_rtl: false,
  },
  {
    code: 'to',
    name: 'Tongan',
    native_name: 'Lea faka-Tonga',
    is_rtl: false,
  },
  {
    code: 'tr',
    name: 'Turkish',
    native_name: 'Türkçe',
    is_rtl: false,
  },
  {
    code: 'tk',
    name: 'Turkmen',
    native_name: 'Türkmençe',
    is_rtl: false,
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    native_name: 'Українська',
    is_rtl: false,
  },
  {
    code: 'ur',
    name: 'Urdu',
    native_name: 'اردو',
    is_rtl: true,
  },
  {
    code: 'ug',
    name: 'Uyghur',
    native_name: 'ئۇيغۇرچە',
    is_rtl: true,
  },
  {
    code: 'uz',
    name: 'Uzbek',
    native_name: 'Oʻzbekcha',
    is_rtl: false,
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    native_name: 'Tiếng Việt',
    is_rtl: false,
  },
  {
    code: 'cy',
    name: 'Welsh',
    native_name: 'Cymraeg',
    is_rtl: false,
  },
  {
    code: 'fy',
    name: 'Western Frisian',
    native_name: 'Frysk',
    is_rtl: false,
  },
  {
    code: 'wo',
    name: 'Wolof',
    native_name: 'Wolof',
    is_rtl: false,
  },
  {
    code: 'xh',
    name: 'Xhosa',
    native_name: 'isiXhosa',
    is_rtl: false,
  },
  {
    code: 'yi',
    name: 'Yiddish',
    native_name: 'ייִדיש',
    is_rtl: true,
  },
  {
    code: 'yo',
    name: 'Yoruba',
    native_name: 'Yorùbá',
    is_rtl: false,
  },
  {
    code: 'zu',
    name: 'Zulu',
    native_name: 'isiZulu',
    is_rtl: false,
  },
]

export const searchLanguage = (term: string): StaticLanguage | null => {
  return (
    languages.find((lang) => Object.values(lang).join('').includes(term)) ??
    null
  )
}

export const getLanguageByCode = (code: string): StaticLanguage | null => {
  return languages.find((lang) => lang.code === code) ?? null
}
