export default {
  payment_keys: [
    {
      integration: 1234567,
      key: 'dummy_payment_key_base64_encoded_token_for_testing_purposes_only',
      gateway_type: 'MIGS',
      iframe_id: null,
      order_id: 12345678,
      redirection_url: 'http://localhost:5000/api/acceptance/post_pay',
      save_card: false,
    },
  ],
  intention_order_id: 12345678,
  id: 'pi_test_dummy123456789abcdef',
  intention_detail: {
    amount: 19900,
    items: [],
    currency: 'EGP',
    billing_data: {
      apartment: 'sympl',
      floor: 'dumy',
      first_name: 'dumy',
      last_name: 'dumy',
      street: 'dumy',
      building: 'dumy',
      phone_number: '+201234567890',
      shipping_method: '',
      city: 'dumy',
      country: 'EG',
      state: 'dumy',
      email: 'test@example.com',
      postal_code: '',
    },
  },
  client_secret: 'dummy_client_secret_for_testing',
  payment_methods: [
    {
      integration_id: 1234567,
      alias: null,
      name: null,
      method_type: 'online',
      currency: 'EGP',
      live: false,
      use_cvc_with_moto: false,
    },
  ],
  special_reference: 'dummy_session_12345',
  extras: {
    creation_extras: {
      ee: 22,
      session_id: 'dummy_session_12345',
      merchant_order_id: 'dummy_session_12345',
    },
    confirmation_extras: null,
  },
  confirmed: false,
  status: 'intended',
  created: '2025-09-10T09:59:00.768111',
  card_detail: null,
  card_tokens: [],
  object: 'paymentintention',
}
