export default {
  paymob_request_id: null,
  intention: {
    id: 'pi_test_dummy123456789abcdef',
    intention_detail: {
      amount: 19900,
      items: [],
      currency: 'EGP',
      billing_data: {
        apartment: 'sympl',
        floor: 'dumy',
        first_name: 'dumy',
        last_name: 'dumy',
        street: 'dumy',
        building: 'dumy',
        phone_number: '+201234567890',
        shipping_method: '',
        city: 'dumy',
        country: 'EG',
        state: 'dumy',
        email: 'test@example.com',
        postal_code: '',
      },
    },
    client_secret: 'dummy_client_secret_for_testing',
    payment_methods: [
      {
        integration_id: 1234567,
        alias: null,
        name: null,
        method_type: 'online',
        currency: 'EGP',
        live: false,
        use_cvc_with_moto: false,
      },
    ],
    special_reference: 'dummy_session_12345',
    extras: {
      creation_extras: { ee: 22, session_id: 'dummy_session_12345' },
      confirmation_extras: null,
    },
    confirmed: false,
    status: 'intended',
    created: '2025-09-10T09:59:00.768111',
    card_detail: null,
    card_tokens: [],
    object: 'paymentintention',
  },
  hmac: 'dummy_hmac_hash_for_webhook_verification_testing_purposes',
  transaction: {
    amount_cents: 19900,
    created_at: '2025-09-10T10:08:58.557810',
    currency: 'EGP',
    error_occured: false,
    has_parent_transaction: false,
    id: 87654321,
    integration_id: 1234567,
    is_3d_secure: true,
    is_auth: true,
    is_capture: false,
    is_refunded: false,
    is_standalone_payment: true,
    is_voided: false,
    order: { id: 12345678 },
    owner: 9876543,
    pending: false,
    source_data: { pan: '4444', sub_type: 'MasterCard', type: 'card' },
    success: true,
    receipt: 'dummy_receipt_123',
    discount_details: [],
    accept_fees: 0,
    shopify_data: null,
  },
}
